Repository TeamKioki/BE, pull requests merged in 2024-08, with the labels that each got.

#2 feat: 엔티티 생성 (#1)
  src/main/java/com/dev/kioki/domain/Bookmark/entity/Bookmark.java
  src/main/java/com/dev/kioki/domain/brand/entity/Brand.java
  src/main/java/com/dev/kioki/domain/brand/entity/enums/BrandType.java
  src/main/java/com/dev/kioki/domain/review/entity/Review.java
  src/main/java/com/dev/kioki/domain/user/entity/Helper.java
  src/main/java/com/dev/kioki/domain/user/entity/User.java
  src/main/java/com/dev/kioki/domain/user/entity/UserProfile.java
  src/main/java/com/dev/kioki/domain/user/entity/enums/FontSize.java
  src/main/java/com/dev/kioki/global/common/BaseEntity.java
Labels: ✨ feature

#4 ✨ Feature: 프로젝트 세팅
  src/main/java/com/dev/kioki/global/common/BaseResponse.java
  src/main/java/com/dev/kioki/global/common/code/BaseCode.java
  src/main/java/com/dev/kioki/global/common/code/BaseErrorCode.java
  src/main/java/com/dev/kioki/global/common/code/ErrorReasonDTO.java
  src/main/java/com/dev/kioki/global/common/code/ReasonDTO.java
  src/main/java/com/dev/kioki/global/common/code/status/ErrorStatus.java
  src/main/java/com/dev/kioki/global/common/code/status/SuccessStatus.java
  src/main/java/com/dev/kioki/global/error/ExceptionAdvice.java
  src/main/java/com/dev/kioki/global/error/GeneralException.java
Labels: ✨ feature

#7 ✨ Feature: 그룹 엔티티 생성
  src/main/java/com/dev/kioki/domain/user/group/entity/Group.java
  src/main/java/com/dev/kioki/domain/user/group/entity/GroupMember.java
Labels: ✨ feature

#10 ✨ Feature: 유저 인증 관련 스웨거 명세 작성
  src/main/java/com/dev/kioki/domain/auth/controller/AuthController.java
  src/main/java/com/dev/kioki/domain/auth/dto/AuthDTO.java
  src/main/java/com/dev/kioki/domain/auth/service/AuthService.java
  src/main/java/com/dev/kioki/domain/auth/service/impl/AuthServiceImpl.java
  src/main/java/com/dev/kioki/domain/user/entity/User.java
  src/main/java/com/dev/kioki/domain/user/entity/UserPage.java
  src/main/java/com/dev/kioki/domain/user/entity/UserProfile.java
Labels: ✨ feature

#19 ✨ Feature: 휴대폰 번호 인증 구현
  build.gradle
  src/main/java/com/dev/kioki/domain/auth/controller/AuthController.java
  src/main/java/com/dev/kioki/domain/auth/converter/AuthConverter.java
  src/main/java/com/dev/kioki/domain/auth/dto/AuthDTO.java
  src/main/java/com/dev/kioki/domain/auth/service/AuthService.java
  src/main/java/com/dev/kioki/domain/auth/service/impl/AuthServiceImpl.java
  src/main/java/com/dev/kioki/global/common/code/status/ErrorStatus.java
  src/main/java/com/dev/kioki/global/error/handler/SmsException.java
  src/main/java/com/dev/kioki/global/redis/RedisConfig.java
  src/main/java/com/dev/kioki/global/redis/RedisUtil.java
  src/main/java/com/dev/kioki/global/sms/SmsUtil.java
  src/main/resources/application.yml
Labels: ✨ feature

#21 ✨ Feature: 유저 인증 기능 구현
  build.gradle
  src/main/java/com/dev/kioki/domain/auth/controller/AuthController.java
  src/main/java/com/dev/kioki/domain/auth/converter/AuthConverter.java
  src/main/java/com/dev/kioki/domain/auth/dto/AuthDTO.java
  src/main/java/com/dev/kioki/domain/user/entity/User.java
  src/main/java/com/dev/kioki/domain/user/entity/enums/UserRole.java
  src/main/java/com/dev/kioki/domain/user/repository/UserRepository.java
  src/main/java/com/dev/kioki/global/common/code/status/ErrorStatus.java
  src/main/java/com/dev/kioki/global/config/WebConfig.java
  src/main/java/com/dev/kioki/global/error/handler/AuthException.java
  src/main/java/com/dev/kioki/global/security/config/SecurityConfig.java
  src/main/java/com/dev/kioki/global/security/filter/CustomLoginFilter.java
  src/main/java/com/dev/kioki/global/security/filter/JwtExceptionFilter.java
  src/main/java/com/dev/kioki/global/security/filter/JwtFilter.java
  src/main/java/com/dev/kioki/global/security/principal/PrincipalDetails.java
  src/main/java/com/dev/kioki/global/security/principal/PrincipalDetailsService.java
  src/main/java/com/dev/kioki/global/security/util/CustomAuthenticationProvider.java
  src/main/java/com/dev/kioki/global/security/util/CustomAuthenticationToken.java
  src/main/java/com/dev/kioki/global/security/util/HttpRequestUtil.java
  src/main/java/com/dev/kioki/global/security/util/HttpResponseUtil.java
  src/main/java/com/dev/kioki/global/security/util/JwtUtil.java
  src/main/resources/application.yml
Labels: ✨ feature

#23 ✨ Feature: 회원가입 기능 구현
  src/main/java/com/dev/kioki/domain/auth/converter/AuthConverter.java
  src/main/java/com/dev/kioki/domain/auth/dto/AuthDTO.java
  src/main/java/com/dev/kioki/domain/auth/service/impl/AuthServiceImpl.java
  src/main/java/com/dev/kioki/domain/user/entity/User.java
  src/main/java/com/dev/kioki/domain/user/repository/UserRepository.java
  src/main/java/com/dev/kioki/global/common/code/status/ErrorStatus.java
  src/main/java/com/dev/kioki/global/validation/annotation/PhoneDuplication.java
  src/main/java/com/dev/kioki/global/validation/validator/PhoneDuplicationValidation.java
Labels: ✨ feature

#25 ✨ Feature: 로그아웃 기능 구현
  src/main/java/com/dev/kioki/global/common/code/status/ErrorStatus.java
  src/main/java/com/dev/kioki/global/security/config/SecurityConfig.java
  src/main/java/com/dev/kioki/global/security/filter/CustomLogoutHandler.java
  src/main/java/com/dev/kioki/global/security/filter/JwtFilter.java
  src/main/java/com/dev/kioki/global/security/util/JwtUtil.java
Labels: ✨ feature

#27 ✨ Feature: 토큰 재발급 기능 구현
  src/main/java/com/dev/kioki/KiokiApplication.java
  src/main/java/com/dev/kioki/domain/auth/controller/AuthController.java
  src/main/java/com/dev/kioki/domain/auth/service/impl/AuthServiceImpl.java
  src/main/java/com/dev/kioki/global/common/code/status/ErrorStatus.java
  src/main/java/com/dev/kioki/global/config/WebConfig.java
  src/main/java/com/dev/kioki/global/security/annotation/ExtractToken.java
  src/main/java/com/dev/kioki/global/security/annotation/ExtractTokenArgumentResolver.java
  src/main/java/com/dev/kioki/global/security/filter/CustomLoginFilter.java
  src/main/java/com/dev/kioki/global/security/util/CustomAuthenticationProvider.java
  src/main/java/com/dev/kioki/global/security/util/CustomAuthenticationToken.java
  src/main/java/com/dev/kioki/global/security/util/JwtUtil.java
Labels: ✨ feature

#29 feat: 그룹 멤버 추가 API (#28)
  src/main/java/com/dev/kioki/domain/group/controller/GroupMemberController.java
  src/main/java/com/dev/kioki/domain/group/converter/GroupMemberConverter.java
  src/main/java/com/dev/kioki/domain/group/dto/GroupRequestDTO.java
  src/main/java/com/dev/kioki/domain/group/dto/GroupResponseDTO.java
  src/main/java/com/dev/kioki/domain/group/repository/GroupRepository.java
  src/main/java/com/dev/kioki/domain/group/service/GroupMemberService.java
Labels: ✨ feature

#31 👷 CI/CD: CI/CD 파이프라인 구축
  .ebextensions-dev/00-makeFiles.config
  .ebextensions-dev/01-set-timezone.config
  .github/workflows/dev_deploy.yml
  .platform/nginx.conf
  Procfile
  src/main/java/com/dev/kioki/global/common/HealthCheckController.java
Labels: 👷ci/cd

#35 feat: 그룹 멤버 프로필 API (#34)
  src/main/java/com/dev/kioki/domain/group/controller/GroupMemberController.java
  src/main/java/com/dev/kioki/domain/group/repository/GroupMemberRepository.java
  src/main/java/com/dev/kioki/domain/group/service/GroupMemberService.java
  src/main/java/com/dev/kioki/global/common/code/status/ErrorStatus.java
Labels: ✨ feature

#37 feat: 그룹 상세 정보 수정 API (#36)
  src/main/java/com/dev/kioki/domain/group/controller/GroupMemberController.java
  src/main/java/com/dev/kioki/domain/group/dto/GroupRequestDTO.java
  src/main/java/com/dev/kioki/domain/group/service/GroupMemberService.java
Labels: ✨ feature

#39 👷 CI/CD: health check 허용 url 설정 (#38)
  src/main/java/com/dev/kioki/global/security/config/SecurityConfig.java
Labels: 👷ci/cd

#41 그룹 멤버 상세 조회 API
  src/main/java/com/dev/kioki/domain/group/controller/GroupMemberController.java
  src/main/java/com/dev/kioki/domain/group/service/GroupMemberService.java
Labels: ✨ feature

#43 feat: 그룹 내 멤버 검색 API (#42)
  src/main/java/com/dev/kioki/domain/group/controller/GroupMemberController.java
  src/main/java/com/dev/kioki/domain/group/repository/GroupMemberRepository.java
  src/main/java/com/dev/kioki/domain/group/service/GroupMemberService.java
Labels: ✨ feature

#45 ✨ Feature: 유저 관련 커스텀 어노테이션 구현
  src/main/java/com/dev/kioki/global/security/annotation/AuthUser.java
  src/main/java/com/dev/kioki/global/security/annotation/AuthUserArgumentResolver.java
  src/main/java/com/dev/kioki/global/security/filter/CustomLoginFilter.java
Labels: ✨ feature

#47 🧹 Chore: application.yml dev local profile분리
  .ebextensions-dev/00-makeFiles.config
  .gitignore
  src/main/resources/application-database.yml
  src/main/resources/application-jwt.yml
  src/main/resources/application-redis.yml
  src/main/resources/application-sms.yml
  src/main/resources/application.yml
Labels: 📝 docs

#51 ✨ Feature: 인증, 인가 실패 처리 로직 추가
  src/main/java/com/dev/kioki/global/common/code/status/ErrorStatus.java
  src/main/java/com/dev/kioki/global/security/config/SecurityConfig.java
  src/main/java/com/dev/kioki/global/security/exception/JwtAccessDeniedHandler.java
  src/main/java/com/dev/kioki/global/security/exception/JwtAuthenticationEntryPoint.java
Labels: ✨ feature

#53 🐛 Fix: CORS, 캐시 컨트롤 헤더 설정 관련 에러
  src/main/java/com/dev/kioki/global/config/SwaggerConfig.java
  src/main/java/com/dev/kioki/global/config/WebConfig.java
Labels: 🐛 bug

#55 🐛 Fix: 허용 OriginPatterns 추가
  src/main/java/com/dev/kioki/global/config/WebConfig.java
Labels: 🐛 bug

#58 ✨ Feature: @AuthUser 설정
  src/main/java/com/dev/kioki/global/config/WebConfig.java
  src/main/java/com/dev/kioki/global/security/config/SecurityConfig.java
Labels: ✨ feature

#59 ✨ Feature: 그룹 api 사용자 인증 처리
  src/main/java/com/dev/kioki/domain/group/controller/GroupMemberController.java
  src/main/java/com/dev/kioki/domain/group/entity/Group.java
  src/main/java/com/dev/kioki/domain/group/entity/GroupMember.java
  src/main/java/com/dev/kioki/domain/group/repository/GroupRepository.java
  src/main/java/com/dev/kioki/domain/group/service/GroupMemberService.java
  src/main/java/com/dev/kioki/domain/group/service/GroupService.java
  src/main/java/com/dev/kioki/global/common/code/status/ErrorStatus.java
Labels: ✨ feature

#60 feat: 회원 가입 시 그룹 생성 기능 추가
  src/main/java/com/dev/kioki/domain/auth/service/impl/AuthServiceImpl.java
Labels: ✨ feature

#64 feat: 그룹 멤버 삭제 API (#63)
  src/main/java/com/dev/kioki/domain/group/controller/GroupMemberController.java
  src/main/java/com/dev/kioki/domain/group/service/GroupMemberService.java
Labels: ✨ feature

#66 feat: 그룹 외 유저 검색 API (#65)
  src/main/java/com/dev/kioki/domain/group/controller/GroupMemberController.java
  src/main/java/com/dev/kioki/domain/user/converter/UserConverter.java
  src/main/java/com/dev/kioki/domain/user/dto/UserResponseDTO.java
  src/main/java/com/dev/kioki/domain/user/repository/UserRepository.java
  src/main/java/com/dev/kioki/domain/user/service/UserQueryService.java
  src/main/java/com/dev/kioki/domain/user/service/UserQueryServiceImpl.java
Labels: ✨ feature

#70 ✨ Feature: S3 PresignedUrl을 활용한 파일 관리 로직 구현
  build.gradle
  src/main/java/com/dev/kioki/global/aws/s3/config/AWSConfig.java
  src/main/java/com/dev/kioki/global/aws/s3/controller/S3Controller.java
  src/main/java/com/dev/kioki/global/aws/s3/dto/PresignedUrlToDownloadDTO.java
  src/main/java/com/dev/kioki/global/aws/s3/dto/PresignedUrlToUploadDTO.java
  src/main/java/com/dev/kioki/global/aws/s3/service/S3Service.java
  src/main/java/com/dev/kioki/global/aws/s3/service/impl/S3ServiceImpl.java
  src/main/resources/application-s3.yml
  src/main/resources/application.yml
Labels: ✨ feature

#72 🐛 Fix: 휴대폰 번호 중복 검증 커스텀 어노테이션 수정
  build.gradle
  src/main/java/com/dev/kioki/global/validation/validator/PhoneDuplicationValidation.java
Labels: 🐛 bug

#83 Feature: 회원 탈퇴 기능 구현
  src/main/java/com/dev/kioki/domain/auth/controller/AuthController.java
  src/main/java/com/dev/kioki/domain/auth/converter/AuthConverter.java
  src/main/java/com/dev/kioki/domain/auth/dto/AuthDTO.java
  src/main/java/com/dev/kioki/domain/auth/service/AuthService.java
  src/main/java/com/dev/kioki/domain/auth/service/impl/AuthServiceImpl.java
  src/main/java/com/dev/kioki/domain/user/entity/User.java
Labels: ✨ feature

#94 ✨ Feature: 문자 인증 인증 번호 형식 변경
  src/main/java/com/dev/kioki/global/sms/SmsUtil.java
Labels: ✨ feature

#95 ♻️ Refactor: 이미지 처리 방식 변경
  src/main/java/com/dev/kioki/domain/auth/converter/AuthConverter.java
  src/main/java/com/dev/kioki/domain/auth/service/impl/AuthServiceImpl.java
  src/main/java/com/dev/kioki/global/aws/s3/controller/S3Controller.java
  src/main/java/com/dev/kioki/global/aws/s3/service/S3Service.java
  src/main/java/com/dev/kioki/global/aws/s3/service/impl/S3ServiceImpl.java
  src/main/java/com/dev/kioki/global/security/config/SecurityConfig.java
Labels: :recycle: refactor
